language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq git-buildpackage
  - sudo apt-get install -qq debhelper
script: git-buildpackage -uc -us
branches:
  only:
    - master
    - saucy
