sudo: required
dist: trusty
language: c
before_script:
  - echo 'deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ xenial main universe' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -yy build-essential colorgcc dpkg-dev debhelper dh-autoreconf git-buildpackage libjemalloc1
  - git fetch origin +upstream:upstream
  - git fetch origin +pristine-tar:pristine-tar
script: >
  gbp buildpackage --git-builder="debuild --set-envvar=CC=$TRAVIS_CC --no-lintian -i'^\.git/|^\.gitignore$|^\.travis.yml$|^README\.md$' -I" -uc -us &&
  cat ../*.changes &&
  debc &&
  lintian --dont-check-part standards-version --fail-on-warnings --color always --info ../*.changes &&
  sudo dpkg --install ../*.deb
env:
  global:
    - TRAVIS_CC=colorgcc
    - DEB_BUILD_OPTIONS='parallel=4'
    - LINTIAN_PROFILE=debian
