language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq git-buildpackage
  - sudo apt-get install -qq debhelper
before_script:
  - git fetch origin +upstream:upstream
  - git fetch origin +pristine-tar:pristine-tar
script: git-buildpackage --git-builder="debuild --no-lintian -i'^\.git/|^\.gitignore$|^\.travis.yml$|^\.gbp\.conf$' -I" -uc -us && lintian --fail-on-warnings --color always --info
branches:
  only:
    - master
    - saucy
