language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq git-buildpackage
  - sudo apt-get install -qq debhelper
before_script:
  - git fetch origin +upstream:upstream
  - git fetch origin +pristine-tar:pristine-tar
script: git-buildpackage -uc -us --no-lintian && lintian --fail-on-warnings --color always --info
branches:
  only:
    - master
    - saucy
